### PR TITLE
Prevent loading of untrusted initrds

### PR DESCRIPTION
**Pull request by alois31**
Using a malicious boot loader specification entry, the kernel could be instructed to load untrusted initrds in two ways:
* Since the kernel was signed, it could be loaded directly, with an arbitrary initrd (since neither systemd-boot nor Linux verify initrds).
* The cmdline our stub received was passed on to the kernel. By loading the stub indirectly via boot loader specification, this could be abused to point the kernel to an arbitrary initrd, as well as instructing it to perform various other fun stuff.

To prevent these security bypasses, the following solution is implemented:
* Use a custom PE loader, just enough to load the kernel, in order not to rely on `LoadImage`. This loader does not need to verify signatures, because we already confirmed using the hash that the kernel is trusted.
* Stop signing kernels on installation, preventing the first bypass.
* Always pass the cmdline built into the stub UKI to the kernel. By virtue of being built-in, this cmdline is trusted, and the second bypass is fixed.

Fixes: https://github.com/nix-community/lanzaboote/issues/65

### CODE REVIEW

**Comment by alois31** [comment]
Please note that this implementation is still a bit rough around the edges. In particular, there are the following known shortcomings or changes in behavior (roughly in ascending order of severity, in my view):

* The kernel image does not get measured into PCR 4 any more. This should be harmless, because its hash already influenced PCR 4 as part of measuring the stub UKI.
* The PE loader is extremely basic: it performs nearly no checks at all, and doesn't support most relocation types. I don't think this is a problem, because we only load trusted Linux kernels.
* NX is not supported. I'm honestly not quite sure how to properly do that given that some pages contain sections with different permissions:
``` 
  0 .setup        00003dc0  0000000001000200  0000000001000200  00000200  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .reloc        00000020  0000000001003fc0  0000000001003fc0  00003fc0  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .compat       00000020  0000000001003fe0  0000000001003fe0  00003fe0  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .text         0082b000  0000000001004000  0000000001004000  00004000  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
```
* Stuff is completely broken on architectures with incoherent instruction caches. This is relevant for supporting AArch64, which I already see in another pull request. This can be easily fixed by flushing the icache after relocating the kernel image, which I think requires a bit of architecture-specific code.

**Comment by nikstur** [comment]
Thanks for the PR! I think @blitz can review this best.

File: rust/stub/src/pe_loader.rs [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    pub entry: extern "efiapi" fn(Handle, SystemTable<Boot>) -> Status,
+}
+
+#[cfg(target_arch = "x86_64")]
+fn flush_instruction_cache(_start: *const u8, _length: usize) {
+    // x86_64 mandates coherent instruction cache
+}
+
+/// Loads and relocates a trusted PE file, returning a structure containing its allocated virtual memory range and entry point.
+pub unsafe fn load(boot_services: &BootServices, file_data: &[u8]) -> uefi::Result<Image> {
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:23]: If this function is marked `unsafe` it should have a `/// # Safety` section. See [here](https://rust-lang.github.io/api-guidelines/documentation.html#function-docs-include-error-panic-and-safety-considerations-c-failure).

That being said, I don't think this function should be marked `unsafe` to begin with, because it should always be safe to call. Is there some situations where it's not?

File: rust/stub/src/pe_loader.rs [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+    let pe = PE::parse(file_data).expect("Malformed PE file");
+
+    // Allocate all memory the image will need in virtual memory.
+    // We follow shim here and allocate as EfiLoaderCode.
+    let mut pos = 0;
+    for section in &pe.sections {
+        assert!(section.virtual_address >= pos);
+        pos = section.virtual_address + section.virtual_size;
+    }
+    let base = boot_services.allocate_pages(
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:33]: `Image` should free the allocated memory on `Drop`. Then it is also safe to use a `&[u8]` slice instead of pointer + size?

File: rust/stub/src/pe_loader.rs [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+/// Loads and relocates a trusted PE file, returning a structure containing its allocated virtual memory range and entry point.
+pub unsafe fn load(boot_services: &BootServices, file_data: &[u8]) -> uefi::Result<Image> {
+    let pe = PE::parse(file_data).expect("Malformed PE file");
+
+    // Allocate all memory the image will need in virtual memory.
+    // We follow shim here and allocate as EfiLoaderCode.
+    let mut pos = 0;
+    for section in &pe.sections {
+        assert!(section.virtual_address >= pos);
+        pos = section.virtual_address + section.virtual_size;
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:31]: This code find the end of the last section? If so you could say:

`pe.sections.iter().map(|s| s.virtual_address + s.virtual_size).max_element()`

This would also remove the limitations that the sections need to be ordered in the PE image.

When your at it, it would help readability to select a better name than `pos`. `virt_end`?

File: rust/stub/src/pe_loader.rs [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+fn flush_instruction_cache(_start: *const u8, _length: usize) {
+    // x86_64 mandates coherent instruction cache
+}
+
+/// Loads and relocates a trusted PE file, returning a structure containing its allocated virtual memory range and entry point.
+pub unsafe fn load(boot_services: &BootServices, file_data: &[u8]) -> uefi::Result<Image> {
+    let pe = PE::parse(file_data).expect("Malformed PE file");
+
+    // Allocate all memory the image will need in virtual memory.
+    // We follow shim here and allocate as EfiLoaderCode.
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:27]: Do you have a pointer to documentation?

File: rust/stub/src/pe_loader.rs [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+    let mut pos = 0;
+    for section in &pe.sections {
+        assert!(section.virtual_address >= pos);
+        pos = section.virtual_address + section.virtual_size;
+    }
+    let base = boot_services.allocate_pages(
+        AllocateType::AnyPages,
+        MemoryType::LOADER_CODE,
+        (pos as usize + 0xfff) >> 12,
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:36]: I don't understand why you take the largest virtual address of the binary and use it as page count here. Can you elaborate?

nit: I'm personally not a fan of C-like type conversions. `usize::try_from(pos).unwrap()` has the charm of being a nop on platforms where the conversion is safe and will fail in case you accidentally use it wrong.

File: rust/stub/src/pe_loader.rs (hunk 2 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs:33]: Or even better, have a small RAII wrapper around `allocate_pages` so we don't leak memory when we fail to load the image.

File: rust/stub/src/pe_loader.rs [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+            );
+            core::ptr::write_bytes(
+                base.add(section.virtual_address as usize + copy_size),
+                0,
+                section.virtual_size as usize - copy_size,
+            );
+        }
+    }
+
+    // Apply image base relocations.
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:57]: I'm not sure what's going on here. Does [relocations](https://docs.rs/goblin/0.6.0/goblin/pe/section_table/struct.SectionTable.html#method.relocations) not work?

**Review by blitz — CHANGES_REQUESTED** [review]
This is a great start. :+1: 

If we work on the safety of the code this will be a great addition and solve #65. I might find an hour or two to help with this, but I'm a bit swamped till FOSDEM.

File: rust/stub/src/main.rs [hunk 7]
```diff
@@ -162,40 +169,26 @@ fn main(handle: Handle, mut system_table: SystemTable<Boot>) -> Status {
...
-            .expect("UEFI refused to load the kernel image. It may not be signed or it may not have an EFI stub.")
-    };
+    let kernel = unsafe { pe_loader::load(system_table.boot_services(), &kernel_data) }
+        .expect("Failed to load the kernel");
 
-    let mut kernel_image = system_table
+    let mut loaded_image = system_table
         .boot_services()
-        .open_protocol_exclusive::<LoadedImage>(kernel_handle)
+        .open_protocol_exclusive::<LoadedImage>(handle)
```
Comment (blitz) [inline rust/stub/src/main.rs:177]: Does anyone know how to create a new UEFI handle? It seems wrong to re-use the lanzaboote handle for the kernel we load. Or is this the way to go?

@RaitoBezarius

File: rust/stub/src/pe_loader.rs (hunk 1 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs]: The function was pretty wildly memory unsafe due to almost no checks being performed. I added some easy checks, moved the unsafety to starting the image and documented it there.

File: rust/stub/src/pe_loader.rs (hunk 2 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs]: I don't see this working since deallocating pages requires boot services. However, I implemented deallocating the kernel if it returns.

File: rust/stub/src/pe_loader.rs (hunk 4 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs]: It's documented in the UEFI spec (e.g. section 2.1.1) that EFI applications get their code loaded as EfiLoaderCode and their data as EfiLoaderData. However, we can't do that since they need to be contiguous. So I checked what shim does in its code, and it turns out it uses EfiLoaderCode for everything.

File: rust/stub/src/pe_loader.rs (hunk 5 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs]: The virtual address is relative to the image base.

File: rust/stub/src/main.rs (hunk 7 above)
Comment (RaitoBezarius) [reply rust/stub/src/main.rs]: We can locate a (set of) handles which can be opened for the LoadedImage protocol using `locate_protocol`: https://docs.rs/uefi/0.1.2/uefi/struct.BootServices.html#method.locate_handle_by_protocol AFAIK

But, it's going to probably return one of the handle we are holding right now.

File: rust/stub/src/pe_loader.rs (hunk 6 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs]: PE has two different kinds of relocations: object relocations are what you linked, and they only get used when linking object files. Image base relocations apply to an executable (or shared library) and use a different mechanism I parse here.

(Side note: using the thing you linked would "work" in the sense that the Linux kernel happens to load, since it does not contain meaningful image base relocations. So would not bothering at all about relocations. Things staying that way is not an assumption I'd be willing to make, since that would silently break things.)

File: rust/stub/src/main.rs (hunk 7 above)
Comment (alois31) [reply rust/stub/src/main.rs]: I don't see a way to allocate a new UEFI handle. LocateProtocol is definitely a bad choice: that returns "the first handle" supporting the protocol, which is some driver or systemd-boot, making it a much worse choice than our own handle. At least the uefi crate documents using `set_image` for pretty much our exact use-case, and shim also does the same.

Comment (RaitoBezarius) [reply rust/stub/src/main.rs]: I do think this method returns the set of *all* handles supporting the protocol, but you're right.

Comment (blitz) [reply rust/stub/src/main.rs]: Thanks for looking into this.

File: rust/stub/src/pe_loader.rs (hunk 4 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs]: Ok.

File: rust/stub/src/pe_loader.rs (hunk 2 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs]: Yes, that's what I meant!

**Comment by blitz** [comment]
@alois31 I've tried to make `Image::load` not `unwrap` and `expect` so much any more. See the commit I pushed into the PR.

File: rust/stub/src/pe_loader.rs [hunk 8]
```diff
@@ -0,0 +1,197 @@
...
+                    let offset_field_entry =
+                        u16::from_ne_bytes(relocations[2 * i + 8..2 * i + 10].try_into().unwrap());
+                    match offset_field_entry >> 12 {
+                        // IMAGE_REL_BASED_ABSOLUTE
+                        0 => {}
+                        ty => todo!("Unhandled relocation type: {ty}"),
+                    }
+                }
+
+                relocations = &relocations[size_of_block..];
```
Comment (blitz) [inline rust/stub/src/pe_loader.rs:126]: This parsing code is pretty hard to understand. goblin already comes with [scroll](https://docs.rs/scroll/0.11.0/scroll/) as a dependency, which we could use here to clear this code up.

Given that we basically only check whether there are any relocations here at all, we could also leave it as is. In this case, I would ask you to leave a comment here about improving the parsing.

PS. I removed the panic on unsupported relocations and chose to return an easily recognizable error instead. This would at least leave the user in the boot menu being able to select another item to boot instead of crashing the system.

**Comment by alois31** [comment]
> @alois31 I've tried to make `Image::load` not `unwrap` and `expect` so much any more. See the commit I pushed into the PR.

I don't see any commits related to load, except for the unsupported relocation one. I have seen the `start` one, but that doesn't touch load (I also don't really like that one, but I will comment on that later today).

File: rust/stub/src/pe_loader.rs (hunk 8 above)
Comment (alois31) [reply rust/stub/src/pe_loader.rs:126]: I'm not too fond of that code either. Incidentally, it actually contains a bug (missing division by 2), and I wondered why it doesn't trigger a panic. Turns out while the Linux kernel has a `.reloc` section with one `IMAGE_REL_BASED_ABSOLUTE` (i.e. pointless) relocation, this is actually not linked in the header. I'm probably going to remove the relocation processing code entirely and just return `UNSUPPORTED` (or abuse `INCOMPATIBLE_VERSION` like you did) whenever encountering any linked relocation table at all.

File: rust/stub/src/pe_loader.rs [hunk 9]
```diff
@@ -151,11 +151,10 @@ impl Image {
         handle: Handle,
         system_table: &SystemTable<Boot>,
         load_options: &CStr16,
-    ) -> Status {
+    ) -> uefi::Result<()> {
         let mut loaded_image = system_table
             .boot_services()
-            .open_protocol_exclusive::<LoadedImage>(handle)
-            .expect("Failed to open the LoadedImage protocol");
+            .open_protocol_exclusive::<LoadedImage>(handle)?;
```
Comment (alois31) [inline rust/stub/src/pe_loader.rs:157]: When the UEFI fails to open `LoadedImage` on our image handle, things are extremely messed up already. I'm not sure if there is any point in even bothering to try to return to the bootloader, which is likely not going to be able to work properly either.

File: rust/stub/src/pe_loader.rs [hunk 10]
```diff
@@ -179,12 +178,10 @@ impl Image {
...
 
         // If the kernel entry point returned, deallocate its image, and restore our loaded image handle.
-        // If it calls Exit(), then we don't get here, and our resources are leaked.
-        // I don't see any way to avoid this.
+        // If the kernel exits boot services, we don't get here and there is no point in freeing memory.
         system_table
             .boot_services()
-            .free_pages(self.image.as_ptr() as u64, bytes_to_pages(self.image.len()))
-            .unwrap_or(());
+            .free_pages(self.image.as_ptr() as u64, bytes_to_pages(self.image.len()))?;
```
Comment (alois31) [inline rust/stub/src/pe_loader.rs:184]: This one is interesting. My thought was "failing to deallocate memory is just a resource leak". However, if this fails (and the UEFI is not extremely buggy), we have attempted a double free because the kernel already freed memory it shouldn't have freed. Given that this violates the `unsafe` contract, I'm actually tempted to panic here instead.

File: rust/stub/src/pe_loader.rs [hunk 11]
```diff
@@ -179,12 +178,10 @@ impl Image {
         let status = (self.entry)(handle, unsafe { system_table.unsafe_clone() });
 
         // If the kernel entry point returned, deallocate its image, and restore our loaded image handle.
-        // If it calls Exit(), then we don't get here, and our resources are leaked.
-        // I don't see any way to avoid this.
+        // If the kernel exits boot services, we don't get here and there is no point in freeing memory.
```
Comment (alois31) [inline rust/stub/src/pe_loader.rs:181]: This should at most be an addition instead of a replacement. I don't mean the kernel calling `ExitBootServices` and then (hopefully) not returning. I really mean `Exit`, which normally returns to the parent. However, since we reuse our image handle for the kernel, it actually returns to systemd-boot, and our resources are leaked.

File: rust/stub/src/pe_loader.rs (hunk 8 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs]: Yes, something like that would be a compromise for the time being.

File: rust/stub/src/pe_loader.rs (hunk 10 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs]: Fair enough. In this case, just leave a comment to explain why.

File: rust/stub/src/pe_loader.rs (hunk 11 above)
Comment (blitz) [reply rust/stub/src/pe_loader.rs]: Ah good point. Feel free to fix!

**Comment by blitz** [comment]
@alois31 With the changes around the relocation handling that you suggested, I would approve this PR. It would be nice to get this into the tree, because then we can tackle #58, which currently prevents users from gracefully recovering their boot when things are messed up. :)

**Comment by alois31** [comment]
I think I have already applied these changes before you posted your last comment (see the last three commits). Feel free to fix #58 before, I need to rebase anyway.

**Review by blitz — APPROVED** [review]
This is coming in :fire: hot :fire: for FOSDEM. ;)

**Comment by blitz** [comment]
Mmh. This broke the CI. I didn't even notice that there were no CI runs here. Not sure what happened... We might need to revert this.

**Comment by blitz** [comment]
```
3885f114a8d6d6e3641da83a0b45366c5777e825 is the first bad commit
commit 3885f114a8d6d6e3641da83a0b45366c5777e825
Author: Alois Wohlschlager <alois1@gmx-topmail.de>
Date:   Mon Jan 23 13:52:24 2023 +0100

    Do not sign the kernel
    
    Malicious boot loader specification entries could be used to make a
    signed kernel load arbitrary unprotected initrds. Since we do not want
    this, do not sign the kernel. This way, the only things allowed to boot
    are our UKI stubs, which do verify the initrd.

 rust/tool/src/install.rs | 8 +++++---
 1 file changed, 5 insertions(+), 3 deletions(-)

```

**Comment by blitz** [comment]
Ah, the tests that check whether we reject an unsigned kernel are now obviously broken... :-D I won't revert, because this is not a functional issue. I hope I can look into this tonight, should be an easy fix. Maybe @nikstur has time as well.
